### PR TITLE
WIP: support Python 3.7

### LINKED ISSUE #20: Support Python 3.7
Apparently, Python3.7 builds fail, see https://github.com/rkern/line_profiler/issues/129 and https://github.com/rkern/line_profiler/issues/132.  

It would be great if we could still get packages on conda-forge.  There seem to be solutions available at https://github.com/rkern/line_profiler/issues/132#issuecomment-418913772 and https://launchpadlibrarian.net/380639231/python-line-profiler_2.1-1build1_2.1-1ubuntu1.diff.gz

Please let me know if I can help.

### PR DESCRIPTION
**Pull request by andreas-h**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

closes #20

Upstream problem is documented in rkern/line_profiler#132, but
upstream seems unresponsive.

This here tries to implement the fix suggested in the upstream issue
by manually running Cython before pip installing.

Haven't had a chance to really test this yet, but was hoping that the CI would take care of that ...

### CODE REVIEW

**Comment by andreas-h** [comment]
seems like there's no ci testing for 3.7 ... so i'll do some testing on my own then, please ignore until then.

**Comment by grlee77** [comment]
@conda-forge-admin, please rerender

**Comment by grlee77** [comment]
I think if you rerender the recipe using the command above it should add CI for 3.7. 

**edit**: my comment above seems to have done the rerender (I wasn't sure if it would since this is not my PR)

**Comment by grlee77** [comment]
I don't think that `find` command syntax is going to work on Windows.  Also, cython will need to be added to the host dependencies. I am trying an alternate solution in #22

**Comment by jakirkham** [comment]
Addressed in PR ( https://github.com/conda-forge/line_profiler-feedstock/pull/22 ). Thanks for the effort here. 🙂

**Pull request closed without merging**
